# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e5676537650ccc5b999afbddee4a5c8ed9fbc2f34f80fd564e3e35f8e0e6d13a0d222a81f1c1263f21ae573f13d157687854c84bc1d11d3003dec8451598c3f

test:
  secret_key_base: 66cc69039bda1910274a513ad99e0dc774c9374a193e8f40aab518b1812537148d9b0c6eeb483bca0363e25364dc825f00251c10f3527b8f321bad66c5e7df11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
